version: "3"

services:
  gateway:
    build: ./gateway
    ports:
      - 3000:3000
    networks:
      - microservice_network
  products:
    build: ./products-microservice
    ports:
      - 8877:8877
    networks:
      - microservice_network

networks: 
    microservice_network:
        driver: bridge


